INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM167','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM167','title','Tirocini Formativi per l''anno 2019',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM167','title','notizia singola 2',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM167','date',NULL,'2019-03-27 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM167','enum','ATTI GIUDIZIARI',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM167','autore','Redazione',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM167','autore','Davive Minnai',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM169','primopiano','true',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM169','title','Stratigrafia delle pendenze ultra-triennali',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM169','title','notizia singola 3',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM169','date',NULL,'2019-04-11 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM169','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM169','autore','Redazione',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM169','autore','Mario Rossi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM36','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM36','title','Bollettino statistico di Marzo 2019',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM36','title','bancale2',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM36','date',NULL,'2019-04-19 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM36','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM459','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM459','title','Normativa',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM459','title','Normativa',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM459','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM463','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM463','title','Programma delle attività 2019',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM463','title','notizia 4',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM463','date',NULL,'2019-03-13 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM463','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM463','autore','Redazione',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM463','autore','Redazione',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM57','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM57','title','Servizi Online',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM57','title','Servizi Online',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM57','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM60','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM60','title','Documenti e Relazioni',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM60','title','Processo telematico',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM60','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM63','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM63','title','Aste Giudiziarie',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM63','title','Aste Giudiziarie',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM63','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM726','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM726','title','Nuovo Palazzo di Giustizia',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM726','title','notizia singola 6',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM726','date',NULL,'2019-03-21 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM726','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM726','autore','Redazione',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM726','autore','Mario Bianchi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM736','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM736','title','Statistiche',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM736','title','Normativa',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM736','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM738','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM738','title','Procedure concorsuali',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM738','title','Normativa',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM738','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM843','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM843','title','Richieste on line',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM843','title','Servizi Online',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM843','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM844','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM844','title','Servizi Online',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM844','title','Servizi Online',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM844','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM851','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM851','title','Tirocini Formativi',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM851','title','Tirocini Formativi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM851','date',NULL,'2019-04-12 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM851','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM851','autore','bianchi',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM851','autore','bianchi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA144','title','Sezioni',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA144','title','Sezioni',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA1880','title','Glossario dei termini giuridici',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA1880','title','Glossario dei termini giuridici',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA22','title','Servizi',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA22','title','Servizi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA30','title','Notizie in primo piano',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA30','title','Notizie in primo piano',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA76','title','Link Istituzionali',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA76','title','Link Istituzionali',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA91','title','home',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA91','title','home',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('DLD646','Title','Titolo test 1',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('DLD646','Title','Titolo test 1',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('DLD650','Title','Titolo test 2',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('DLD650','Title','Titolo test 2',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG1167','Title','Informazioni',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG1167','Title','Informazioni',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG1196','Title','Informazioni',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG1196','Title','Informazioni',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG1530','Title','Accesso ai servizi di cancelleria (Polisweb)',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG1530','Title','Accesso ai servizi di cancelleria (Polisweb)',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG2','Title','Hello, world!',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG2','Title','Hello, world!',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG3','Title','Heading',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG3','Title','Heading',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG346','Title','Struttura degli Uffici',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG346','Title','Info Organizzazione',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG351','Title','Informazioni Sezione Magistrati',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG351','Title','Info Sezione Magistrati',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG353','Title','Dove siamo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG353','Title','Info Dove Siamo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG355','Title','Info Uffici e Cancellerie',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG355','Title','Info Uffici e Cancellerie',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG357','Title','Info Contatti',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG357','Title','Info Contatti',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG371','Title','Info Per il Cittadino',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG371','Title','Info Per il Cittadino',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG373','Title','Info Per il Professionista',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG373','Title','Info Per il Professionista',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG375','Title','Info Per l''Amministrazione',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG375','Title','Info Per l''Amministrazione',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG377','Title','Info Come fare per',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG377','Title','Info Come fare per',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG426','Title','Info Amministrazione Trasparente',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG426','Title','Info Amministrazione Trasparente',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG428','Title','Info Per Sezione Penale',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG428','Title','Info Per Sezione Penale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG430','Title','Info Per Bilancio',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG430','Title','Info Per Bilancio',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG499','Title','Info Per Sezione Civile',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG499','Title','Info Per Sezione Civile',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG503','Title','Info Per Sezione Amministrativa',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG503','Title','Info Per Sezione Amministrativa',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG505','Title','Info Per Sezione Lavoro',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG505','Title','Info Per Sezione Lavoro',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG666','Title','Frequently Asked Questions',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG666','Title','Info Per le F.A.Q.',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG920','Title','Informazioni sul Presidente di Tribunale',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG920','Title','Informazioni sul Presidente di Tribunale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1050','nome','Dott.ssa Mary Carmisciano',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1050','nome','Dott.ssa Mary Carmisciano',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1064','nome','Dott.ssa Maria Saieva',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1064','nome','Dott.ssa Maria Saieva',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1068','nome','Dott. Michele Ruvolo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1068','nome','Dott. Michele Ruvolo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1155','nome','Dirigenza Amministrativa',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1155','nome','Dirigenza Amministrativa',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1165','nome','Dott. Fabio Maiani',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1165','nome','Dott. Fabio Maiani',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1172','nome','Segreteria di Presidenza',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1172','nome','Segreteria di Presidenza',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1177','nome','Dott. Gaspare Ferro',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1177','nome','Dott. Gaspare Ferro',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1180','nome','Rosanna Gucciardi',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1180','nome','Rosanna Gucciardi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1185','nome','Lucia Raineri',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1185','nome','Lucia Raineri',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1304','nome','Tribunale di Marsala',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1304','nome','Tribunale di Marsala',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1312','nome','Dott.ssa Alessandra Camassa',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1312','nome','Dott.ssa Alessandra Camassa',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2068','nome','Dott.ssa Francesca Bellafiore',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2068','nome','Dott.ssa Francesca Bellafiore',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2072','nome','Dott.ssa Mary Carmisciano',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2072','nome','Dott.ssa Mary Carmisciano',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2074','nome','Dott.ssa Francescamaria Piruzza',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2074','nome','Dott.ssa Francescamaria Piruzza',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2076','nome','Dott. Francesco Paolo Pizzo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2076','nome','Dott. Francesco Paolo Pizzo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2078','nome','Dott.ssa Maria Saieva',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2078','nome','Dott.ssa Maria Saieva',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2086','nome','Dott.ssa Tiziana Barone',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2086','nome','Dott.ssa Tiziana Barone',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2088','nome','Dott. Marcello Bellomo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2088','nome','Dott. Marcello Bellomo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2090','nome','Dott.ssa Monica D''Angelo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2090','nome','Dott.ssa Monica D''Angelo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2092','nome','Dott.ssa Marchesina Palermo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2092','nome','Dott.ssa Marchesina Palermo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2094','nome','Dott.ssa Filippetta Signorello',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2094','nome','Dott.ssa Filippetta Signorello',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2096','nome','Dott. Matteo Torre',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2096','nome','Dott. Matteo Torre',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2098','nome','Dott.ssa Sebastiana Zuppardi',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2098','nome','Dott.ssa Sebastiana Zuppardi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2101','nome','Dott.ssa Cinzia Immordino',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2101','nome','Dott.ssa Cinzia Immordino',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2106','nome','Dott. Andrea Marangoni',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2106','nome','Dott. Andrea Marangoni',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2110','nome','Dott.ssa Caterina Greco',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2110','nome','Dott.ssa Caterina Greco',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2112','nome','Dott. Filippo Ruggiero',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2112','nome','Dott. Filippo Ruggiero',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2114','nome','Dott. Marcello Bellomo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2114','nome','Dott. Marcello Bellomo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2116','nome','Dott.ssa Monica D''Angelo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2116','nome','Dott.ssa Monica D''Angelo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2118','nome','Dott.ssa Filippetta Signorello',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2118','nome','Dott.ssa Filippetta Signorello',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2122','nome','Dott.ssa Tiziana Barone',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2122','nome','Dott.ssa Tiziana Barone',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2127','nome','Dott.ssa Rosita Cosentino',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2127','nome','Dott.ssa Rosita Cosentino',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2131','nome','Dott.ssa Marchesina Palermo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2131','nome','Dott.ssa Marchesina Palermo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2134','nome','Dott.ssa Sebastiana Zuppardi',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2134','nome','Dott.ssa Sebastiana Zuppardi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2139','nome','Dott.ssa Cinzia Immordino',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2139','nome','Dott.ssa Cinzia Immordino',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2141','nome','Dott.ssa Francescamaria Piruzza',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2141','nome','Dott.ssa Francescamaria Piruzza',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2166','nome','Dott. Vito Saladino',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2166','nome','Dott. Vito Saladino',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2171','nome','Dott.ssa Mariapia Blanda',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2171','nome','Dott.ssa Mariapia Blanda',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2173','nome','Dott. Lorenzo Chiaramonte',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2173','nome','Dott. Lorenzo Chiaramonte',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2176','nome','Dott. Matteo Giacalone',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2176','nome','Dott. Matteo Giacalone',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2178','nome','Dott.ssa Francesca Maniscalchi',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2178','nome','Dott.ssa Francesca Maniscalchi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2180','nome','Dott.ssa Iole Moricca',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2180','nome','Dott.ssa Iole Moricca',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2182','nome','Dott. Francesco Paolo Pizzo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2182','nome','Dott. Francesco Paolo Pizzo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2184','nome','Dott.ssa Sara Quittino',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2184','nome','Dott.ssa Sara Quittino',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2186','nome','Dott. Mario Faillaci',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2186','nome','Dott. Mario Faillaci',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2188','nome','Dott. Giorgio Lo Verde',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2188','nome','Dott. Giorgio Lo Verde',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2190','nome','Dott.ssa Giuseppina Montericcio',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2190','nome','Dott.ssa Giuseppina Montericcio',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2192','nome','Avv. Ernesto Vallone',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2192','nome','Avv. Ernesto Vallone',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2194','nome','Avv. Leonardo Bruno Vivona',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2194','nome','Avv. Leonardo Bruno Vivona',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2198','nome','Dott. Riccardo Alcamo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2198','nome','Dott. Riccardo Alcamo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2200','nome','Dott.ssa Annalisa Amato',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2200','nome','Dott.ssa Annalisa Amato',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2202','nome','Dott. Francesco Parrinello',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2202','nome','Dott. Francesco Parrinello',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2213','nome','Giuseppa Valenti',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2213','nome','Giuseppa Valenti',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2215','nome','Maria Pia Sciacca (Operatore Giudiziario F2)',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH2215','nome','Maria Pia Sciacca (Operatore Giudiziario F2)',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC655','titolo','Test come fare per',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC655','titolo','Test come fare per',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3111','titolo','e',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3111','titolo','e',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC658','titolo','Procedura di test 2',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC658','titolo','Procedura di test 2',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG142','Title','Chi siamo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG142','Title','Info Il Tribunale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3141','titolo','3.1.03 - Deposito atti',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3141','titolo','3.1.03 - Deposito atti',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3143','titolo','3.1.04 - Richiesta rilascio copie (atti, sentenze, decreti ingiuntivi, ecc.)',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3143','titolo','3.1.04 - Richiesta rilascio copie (atti, sentenze, decreti ingiuntivi, ecc.)',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3148','titolo','3.1.05 - Richiesta /Rilascio certificati',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3148','titolo','3.1.05 - Richiesta /Rilascio certificati',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3150','titolo','3.1.06 – Richiesta informazioni sullo stato del procedimento',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3150','titolo','3.1.06 – Richiesta informazioni sullo stato del procedimento',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3159','titolo','3.2.01 - Accettazione dell’eredità con il beneficio dell’inventario',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3159','titolo','3.2.01 - Accettazione dell’eredità con il beneficio dell’inventario',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3161','titolo','3.2.02 - Rinuncia all’eredità',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3161','titolo','3.2.02 - Rinuncia all’eredità',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3163','titolo','3.2.03 - Eredità giacente: nomina del curatore',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3163','titolo','3.2.03 - Eredità giacente: nomina del curatore',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3165','titolo','3.2.04 - Inventario',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3165','titolo','3.2.04 - Inventario',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3167','titolo','3.2.05 - Certificato di eredità',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3167','titolo','3.2.05 - Certificato di eredità',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3169','titolo','3.2.06 - Apposizione dei sigilli su beni ereditati',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3169','titolo','3.2.06 - Apposizione dei sigilli su beni ereditati',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3174','titolo','3.2.07 - Nomina pubblico ufficiale per inventario',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3174','titolo','3.2.07 - Nomina pubblico ufficiale per inventario',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3178','titolo','3.2.08 - Accettazione incarico di esecutore testamentario',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3178','titolo','3.2.08 - Accettazione incarico di esecutore testamentario',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG342','Title','Comune',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG342','Title','Info Competenza Territoriale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3270','titolo','3.3.01 - Separazione Consensuale',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3270','titolo','3.3.01 - Separazione Consensuale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3272','titolo','3.6.02 Istanza di ammissione al passivo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3272','titolo','3.6.02 Istanza di ammissione al passivo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3266','titolo','3.6.01 - Istanza di fallimento',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3266','titolo','3.6.01 - Istanza di fallimento',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3279','titolo','3.6.03 - Certificato pendenza procedure concorsuali',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3279','titolo','3.6.03 - Certificato pendenza procedure concorsuali',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3281','titolo','3.6.04 - Concordato preventivo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3281','titolo','3.6.04 - Concordato preventivo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3274','titolo','3.3.01 - Separazione Consensuale',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3274','titolo','3.3.01 - Separazione Consensuale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3284','titolo','3.6.05 - Certificato di assenza si procedure fallimentari',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3284','titolo','3.6.05 - Certificato di assenza si procedure fallimentari',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG3287','Title','3.6.06 - Accordo di ristrutturazione dei debiti',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG3287','Title','3.6.06 - Accordo di ristrutturazione dei debiti',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3286','titolo','3.3.02 - Divorzio Congiunto',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3286','titolo','3.3.02 - Divorzio Congiunto',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3288','titolo','3.6.06 - Accordo di ristrutturazione dei debiti',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3288','titolo','3.6.06 - Accordo di ristrutturazione dei debiti',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3291','titolo','3.3.03 - La Modifica Delle Condizioni Di Separazione O Di Divorzio 	  	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3291','titolo','3.3.03 - La Modifica Delle Condizioni Di Separazione O Di Divorzio 	  	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3294','titolo','3.3.04 - Adozione Di Una Persona Maggiorenne 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3294','titolo','3.3.04 - Adozione Di Una Persona Maggiorenne 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3292','titolo','3.6.07 - Esdebitazione del fallimento',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3292','titolo','3.6.07 - Esdebitazione del fallimento',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3296','titolo','3.3.05 - Separazione Giudiziale',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3296','titolo','3.3.05 - Separazione Giudiziale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3298','titolo','3.6.08 - Ammissione tardiva dei crediti',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3298','titolo','3.6.08 - Ammissione tardiva dei crediti',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3301','titolo','3.3.06 - Provvedimenti Relativi Al Mantenimento Dei Figli 	  	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3301','titolo','3.3.06 - Provvedimenti Relativi Al Mantenimento Dei Figli 	  	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3305','titolo','3.3.06 - Provvedimenti Relativi Al Mantenimento Dei Figli 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3305','titolo','3.3.06 - Provvedimenti Relativi Al Mantenimento Dei Figli 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3304','titolo','3.7.01 - Ammortamento della cambiale - smarrita, sottratta o distrutta',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3304','titolo','3.7.01 - Ammortamento della cambiale - smarrita, sottratta o distrutta',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3308','titolo','3.3.07 - Autorizzazione Ad Atti Relativi A Beni Della Comunione Legale Tra Coniugi',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3308','titolo','3.3.07 - Autorizzazione Ad Atti Relativi A Beni Della Comunione Legale Tra Coniugi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3309','titolo','3.7.02 - Ammortamento buoni fruttiferi e libretti di risparmio – smarriti, sottratti o distrutti',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3309','titolo','3.7.02 - Ammortamento buoni fruttiferi e libretti di risparmio – smarriti, sottratti o distrutti',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3312','titolo','3.3.08 - Legittimazione Dei Figli 	  	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3312','titolo','3.3.08 - Legittimazione Dei Figli 	  	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3313','titolo','3.7.03 - Ammortamento di assegni – smarriti, sottratti o distrutti',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3313','titolo','3.7.03 - Ammortamento di assegni – smarriti, sottratti o distrutti',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3316','titolo','3.3.09 - Divorzio Giudiziale 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3316','titolo','3.3.09 - Divorzio Giudiziale 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3318','titolo','3.7.04 - Riabilitazione del protestato',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3318','titolo','3.7.04 - Riabilitazione del protestato',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3319','titolo','3.3.10 - Ricorso A Tutela Del Coniuge Separato O Divorziato 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3319','titolo','3.3.10 - Ricorso A Tutela Del Coniuge Separato O Divorziato 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3322','titolo','3.7.05 - Istanza di riabilitazione a seguito di protesti',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3322','titolo','3.7.05 - Istanza di riabilitazione a seguito di protesti',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3323','titolo','3.4.01 - Ordine Di Protezione Contro Gli Abusi Familiari 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3323','titolo','3.4.01 - Ordine Di Protezione Contro Gli Abusi Familiari 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3327','titolo','3.4.02 - Interdizione E Inabilitazione 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3327','titolo','3.4.02 - Interdizione E Inabilitazione 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3326','titolo','3.8.01 - Richiesta/rilascio copie atti processuali e provvedimenti dei magistrati',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3326','titolo','3.8.01 - Richiesta/rilascio copie atti processuali e provvedimenti dei magistrati',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3330','titolo','3.4.03 - Amministrazione Di Sostegno 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3330','titolo','3.4.03 - Amministrazione Di Sostegno 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3332','titolo','3.8.02 - Richiesta/rilascio certificazioni relative e connesse ai procedimenti penali',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3332','titolo','3.8.02 - Richiesta/rilascio certificazioni relative e connesse ai procedimenti penali',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3333','titolo','3.4.04 - Autorizzazioni Al Rilascio Del Passaporto O Di Documento Valido Per L’espatrio Per Minori O Per Persone Con Figli Minori 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3333','titolo','3.4.04 - Autorizzazioni Al Rilascio Del Passaporto O Di Documento Valido Per L’espatrio Per Minori O Per Persone Con Figli Minori 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3335','titolo','3.8.03 - Istanza di rimborso delle indennità dovute ai testimoni',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3335','titolo','3.8.03 - Istanza di rimborso delle indennità dovute ai testimoni',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3338','titolo','3.4.05 - Procedimenti Relativi Agli Atti Dello Stato Civile 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3338','titolo','3.4.05 - Procedimenti Relativi Agli Atti Dello Stato Civile 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3340','titolo','3.8.04 - Richiesta di permesso di colloquio in carcere',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3340','titolo','3.8.04 - Richiesta di permesso di colloquio in carcere',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3342','titolo','3.4.06 - Tutele 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3342','titolo','3.4.06 - Tutele 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3346','titolo','3.4.07 - Atti Di Straordinaria Amministrazione In Favore Di Un Minore 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3346','titolo','3.4.07 - Atti Di Straordinaria Amministrazione In Favore Di Un Minore 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3343','titolo','3.8.05 - Impugnazioni di sentenza dibattimentali e del gip',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3343','titolo','3.8.05 - Impugnazioni di sentenza dibattimentali e del gip',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3347','titolo','3.8.06 - Richieste al giudice di esecuzione (ex art.665 c.p.p. e seguenti)',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3347','titolo','3.8.06 - Richieste al giudice di esecuzione (ex art.665 c.p.p. e seguenti)',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3355','titolo','3.4.08 - Autorizzazioni Del Giudice Tutelare E Del Tribunale Relative A Persone Incapaci Di Agire 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3355','titolo','3.4.08 - Autorizzazioni Del Giudice Tutelare E Del Tribunale Relative A Persone Incapaci Di Agire 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3359','titolo','3.8.07 - Richiesta liquidazione onorari ausiliari del giudice (professionisti, tecnici, etc)',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3359','titolo','3.8.07 - Richiesta liquidazione onorari ausiliari del giudice (professionisti, tecnici, etc)',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3360','titolo','3.4.09 - Dichiarazione Di Assenza',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3360','titolo','3.4.09 - Dichiarazione Di Assenza',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3363','titolo','3.8.08 - Consultazione atti e fascicoli',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3363','titolo','3.8.08 - Consultazione atti e fascicoli',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3365','titolo','3.4.10 - Dichiarazione Di Morte Presunta 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3365','titolo','3.4.10 - Dichiarazione Di Morte Presunta 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3367','titolo','3.8.09 - Opposizione al decreto penale',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3367','titolo','3.8.09 - Opposizione al decreto penale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3368','titolo','3.4.11 - Autorizzazioni Del Giudice Tutelare (Relative) A Minori 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3368','titolo','3.4.11 - Autorizzazioni Del Giudice Tutelare (Relative) A Minori 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3371','titolo','3.8.10 - Pagamento del decreto penale',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3371','titolo','3.8.10 - Pagamento del decreto penale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3373','titolo','3.4.12 - Autorizzazioni Al Rilascio Del Passaporto O Di Documento Valido Per L’espatrio 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3373','titolo','3.4.12 - Autorizzazioni Al Rilascio Del Passaporto O Di Documento Valido Per L’espatrio 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3374','titolo','3.8.11 - Patrocinio a spese dello stato nel processo penale',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3374','titolo','3.8.11 - Patrocinio a spese dello stato nel processo penale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3377','titolo','3.9.01 - Iscrizioni all’albo dei c.t.u. e dei periti',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3377','titolo','3.9.01 - Iscrizioni all’albo dei c.t.u. e dei periti',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3379','titolo','3.9.02 - Asseverazione',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3379','titolo','3.9.02 - Asseverazione',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3381','titolo','3.5.01 - Conversione Del Pignoramento (Immobiliare) 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3381','titolo','3.5.01 - Conversione Del Pignoramento (Immobiliare) 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3382','titolo','3.9.03 - Atto di notorietà',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3382','titolo','3.9.03 - Atto di notorietà',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3385','titolo','3.5.02 - Istanza Di Vendita 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3385','titolo','3.5.02 - Istanza Di Vendita 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3386','titolo','3.9.04 - Iscrizione al registro stampa',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3386','titolo','3.9.04 - Iscrizione al registro stampa',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3388','titolo','3.5.03 - Istanza Di Sospensione Concordata (Immobiliare) 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3388','titolo','3.5.03 - Istanza Di Sospensione Concordata (Immobiliare) 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3391','titolo','3.5.04 - Intervento Di Creditori 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3391','titolo','3.5.04 - Intervento Di Creditori 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3393','titolo','3.5.05 - Certificato Di Assenza O Di Pendenza Di Procedure Esecutive Immobiliari 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3393','titolo','3.5.05 - Certificato Di Assenza O Di Pendenza Di Procedure Esecutive Immobiliari 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3395','titolo','3.5.06 - Espropriazione Mobiliare Presso Il Debitore 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3395','titolo','3.5.06 - Espropriazione Mobiliare Presso Il Debitore 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3397','titolo','3.5.07 - Espropriazione Presso Terzi 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3397','titolo','3.5.07 - Espropriazione Presso Terzi 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3399','titolo','3.5.08 - Esecuzioni In Forma Specifica 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3399','titolo','3.5.08 - Esecuzioni In Forma Specifica 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3403','titolo','3.5.10 - Procedimento Di Riscossione Speciale 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3403','titolo','3.5.10 - Procedimento Di Riscossione Speciale 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3405','titolo','3.5.11 - Conversione Del Pignoramento (Mobiliare) 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3405','titolo','3.5.11 - Conversione Del Pignoramento (Mobiliare) 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3407','titolo','3.5.12 - Certificato Di Assenza O Di Pendenza Di Procedure Esecutive Mobiliari 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3407','titolo','3.5.12 - Certificato Di Assenza O Di Pendenza Di Procedure Esecutive Mobiliari 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3409','titolo','3.5.13 - Espropriazione Di Beni Immobiliari 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3409','titolo','3.5.13 - Espropriazione Di Beni Immobiliari 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3411','titolo','3.5.14 - Istanza Di Sospensione Concordata (Mobiliare) 	',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3411','titolo','3.5.14 - Istanza Di Sospensione Concordata (Mobiliare) 	',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3401','titolo','3.5.09 - Ricorso Per Proroga Dell’esecuzione Di Sfratto',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3401','titolo','3.5.09 - Ricorso Per Proroga Dell’esecuzione Di Sfratto',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3414','titolo','3.9.05 - Emissione ordini di pagamento testimoni, giudici popolari e giudici onorari di tribunale',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3414','titolo','3.9.05 - Emissione ordini di pagamento testimoni, giudici popolari e giudici onorari di tribunale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3416','titolo','3.9.06 - Rilascio certificazioni fiscali',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3416','titolo','3.9.06 - Rilascio certificazioni fiscali',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3418','titolo','3.9.07 - Richiesta/rilascio informazioni relative al titolo e sua corrispondenza con i dati riportati sulle cartelle esattoriali',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3418','titolo','3.9.07 - Richiesta/rilascio informazioni relative al titolo e sua corrispondenza con i dati riportati sulle cartelle esattoriali',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3420','titolo','3.9.08 - Registrazione delle vendite con riserva di proprietà',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3420','titolo','3.9.08 - Registrazione delle vendite con riserva di proprietà',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3184','titolo','3.1.01 - Iscrizione a ruolo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3184','titolo','3.1.01 - Iscrizione a ruolo',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA673','title','F.A.Q.',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA673','title','F.A.Q.',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM165','primopiano','true',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM165','title','Linee guida in materia di violenza di genere e violenza domestica',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM165','title','notizia singola 1',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM165','date',NULL,'2019-04-01 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM165','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM165','autore','Redazione',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM165','autore','Mario Bianchi',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3139','titolo','3.1.02 - Patrocinio a spese dello stato nel processo civile',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('PRC3139','titolo','3.1.02 - Patrocinio a spese dello stato nel processo civile',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG1175','Title','Informazioni',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG1175','Title','Informazioni',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG745','Title','Lista dei Link utili',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG745','Title','Lista dei Link utili',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM743','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM743','title','Moduli',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM743','title','Servizi Online',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM743','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM741','primopiano','false',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM741','title','Tirocinio formativo',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM741','title','Aste Giudiziarie',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTM741','enum','',NULL,NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1022','nome','Dott.ssa Francesca Bellafiore',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH1022','nome','Dott.ssa Francesca Bellafiore',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH3639','nome','Dott.ssa Filippetta Signorello',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('SCH3639','nome','Dott.ssa Filippetta Signorello',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA71','title','Trasparenza',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CTA71','title','Trasparenza',NULL,NULL,'en');
