INSERT INTO resourcerelations (resid,refcategory) VALUES ('651','moduli');
INSERT INTO resourcerelations (resid,refcategory) VALUES ('647','moduli');
INSERT INTO resourcerelations (resid,refcategory) VALUES ('647','cittadino');
INSERT INTO resourcerelations (resid,refcategory) VALUES ('647','come_fare_per');
INSERT INTO resourcerelations (resid,refcategory) VALUES ('647','denunce_e_querele');
INSERT INTO resourcerelations (resid,refcategory) VALUES ('2796','moduli');
INSERT INTO resourcerelations (resid,refcategory) VALUES ('2796','cittadino');
INSERT INTO resourcerelations (resid,refcategory) VALUES ('2796','come_fare_per');
INSERT INTO resourcerelations (resid,refcategory) VALUES ('2796','allegati');
